### ISSUE TITLE
Dont write into `Path(__file__).parent / "resources"`

### ISSUE THREAD

**Issue by Conni2461** [matthiaskoenig/pymetadata#51]
### Checklist

- [x] I looked through [similar issues on GitHub](https://github.com/matthiaskoenig/pymetadata/issues).

### Question

So a couple of weeks back @cheriimoya and I wanted to package [BayModTS](https://github.com/Systems-Theory-in-Systems-Biology/BayModTS) using nix to streamline the getting started process. The nix package manager will allos us to only `cd` into the `BayModTS` directory and then run `nix develop` and we end up in a shell with a correctly setup environment with all python deps. This is also already working here: https://github.com/helsinki-systems/BayModTS/tree/feat/nix_take3 and we provide some getting started [docs](https://github.com/helsinki-systems/BayModTS/blob/feat/nix_take3/nix_instructions.md).

This problem that we had to workaround was that `pymetadata` write into its own install directory and because the `/nix/store` (where all packages will be installed to) is readonly for all users (besides the nix users, this is simplified), `pymetadata` does not work because it tries to write data into the `RESOURCES_DIR` with for use is inside `/nix/store` so not writable. We then work around this issue by changing the resource directory path to `/tmp/pymetadata/resources` and we have to manually copy over the files prior to using `pymetadata`, as follows

```bash
mkdir -pv /tmp/pymetadata
git clone -b 0.4.2 https://github.com/matthiaskoenig/pymetadata.git /tmp/pymetadata-src
cp -vr /tmp/pymetadata-src/src/pymetadata/resources /tmp/pymetadata
```

My idea now was that maybe we can change this behaivor and use `$HOME/.cache/pymetadata/resources` as a directory to write data to, and before writing anything we check if this directory `resources` directory exists and if not we copy over the files from the install directory, so basically `Path(__file__).parent / "resources"`.

Does this make sense? Or do you have a different idea on how to solve this issue? I'm also not sure if we need to take windows into account? 

I would be available to do these changes myself, i just wanted to check in with you if you okay with that and give a little more context :D

**Comment by matthiaskoenig** [comment]
I improved the handling of the cache path. The path now lies in 
```python
CACHE_PATH: Path = Path.home() / ".cache" / "pymetadata"
```
which should be writable on most systems. In addition you can just customize the location to a writeable dir via doing the following when using pymetadata:

```python
import pymetadata
pymetadata.CACHE_PATH = <custom_path>
```
Let me know if this works. Making a release in a min.

**Comment by Conni2461** [comment]
really nice, thank you very much. Works now like a charm without any patch applied
